name: Test setup
inputs:
  pull_token:
    description: "Token to use for private repo access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.85

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "stable"
        cache-directories: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
