[package]
name = "dummy-range"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# sp1
sp1-zkvm.workspace = true

# op-succinct
op-succinct-client-utils.workspace = true
