{
 "title": "Proof Requests",
 "description": "The number of proof requests in each stage.",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Proposer Progress",
   "type": "timeseries",
   "description": "The status of the L2OutputOracle based on the finalized L2 block, the highest proven block, the minimum block for an aggregate proof and more.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{\n  __name__=~\"op_succinct_proposer_.*_l2_finalized_block|op_succinct_proposer_.*_latest_contract_l2_block|op_succinct_proposer_.*_highest_proven_contiguous_l2_block|op_succinct_proposer_.*_min_block_to_prove_to_agg\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proof Request Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{\n  __name__=~\"op_succinct_proposer_.*_num_proving|op_succinct_proposer_.*_num_witness_gen|op_succinct_proposer_.*_num_unrequested\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Over Time (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{\n  __name__=~\"op_succinct_proposer_.*_error_count|op_succinct_proposer_.*_prove_failures|op_succinct_proposer_.*_witness_gen_failures\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Heap Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}