#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unused)]
//! This lib re-exports the contract bindings.

use alloy_sol_types::sol;

#[cfg_attr(rustfmt, rustfmt_skip)]
mod codegen;

#[cfg_attr(rustfmt, rustfmt_skip)]
pub use codegen::*;

// Hand-written types shared across crates.
// These are not generated by forge bind because they need identical layout
// across fault-proof and host-utils.
sol! {
    /// The L2 output used for computing output roots.
    struct L2Output {
        uint64 zero;
        bytes32 l2_state_root;
        bytes32 l2_storage_hash;
        bytes32 l2_claim_hash;
    }
}
