[package]
name = "op-succinct-celestia-utils"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]

# local
op-succinct-client-utils.workspace = true
op-succinct-host-utils.workspace = true

# kona
kona-preimage.workspace = true
kona-proof.workspace = true
kona-rpc.workspace = true

# hana
hana-host.workspace = true
hana-oracle.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true

# general
anyhow.workspace = true
async-trait.workspace = true
