{
 "title": "Proposer Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Finalized L2 Block Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "op_succinct_fp_finalized_l2_block_number",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Game L2 Block Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "op_succinct_fp_latest_game_l2_block_number",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Games Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_succinct_fp_games_created" }
   ]
  }
 ]
}