#!/bin/bash
# This script is used to run the Kurtosis test suite for the Optimism stack.
# It sets up the environment, builds the necessary images, and runs the tests.
# It requires Docker and Kurtosis to be installed and configured.
# Ensure that Docker is running and Kurtosis is installed before executing this script.

kurtosis run github.com/ethpandaops/optimism-package --args-file https://gist.githubusercontent.com/vcastellm/43d9c74c752435c934114841e1039cc2/raw/a63e5c793c83e1fa8ca8b257f4d1dcbe006dfa52/kurtosis-op-stack.yaml --enclave op
cast send --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 0x8943545177806ED17B9F23F0a21ee5948eCaa776 --value 10ether --rpc-url $(kurtosis port print op op-el-1-op-geth-op-node-op-kurtosis rpc)
docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d postgres

# Create the env file content
cat >.env <<EOF
# This file is automatically generated by the script.
# Do not edit this file directly.

PRIVATE_KEY=bcdf20249abf0ed6d944c0288fad489e33f66b3960d9e6229c1cd214ed3bbe31
VERIFIER_ADDRESS=0xb4B46bdAA835F8E4b4d8e208B6559cD267851051
OP_SUCCINCT_MOCK=true
OP_SUCCINCT_AGGLAYER=true
L2OO_ADDRESS=0x703848F4c85f18e3acd8196c8eC91eb0b7Bd0797
MAX_BLOCK_RANGE_PER_SPAN_PROOF=4
MAX_CONCURRENT_PROOF_REQUESTS=1
MAX_CONCURRENT_WITNESS_GEN=1
SUBMISSION_INTERVAL=1
AGG_PROOF_MODE=compressed

DATABASE_URL=postgres://postgres:mysecretpassword@localhost:5432/postgres
RANGE_PROOF_INTERVAL=4

L1_RPC=http://$(kurtosis port print op el-1-geth-teku rpc)
L1_BEACON_RPC=$(kurtosis port print op cl-1-teku-geth http)
L2_RPC=$(kurtosis port print op op-el-1-op-geth-op-node-op-kurtosis rpc)
L2_NODE_RPC=$(kurtosis port print op op-cl-1-op-node-op-geth-op-kurtosis http)

EOF

# Print the contents of the .env file
echo "Environment variables have been written to .env file:"
cat .env

just deploy-mock-verifier
just deploy-oracle
cargo run --bin multi --release
