name: Cost Estimator (1000 blocks) # Disabled because it requires more resource than current runner. Integration tests also include cost-estimator runs for 5 blocks.

on:
  workflow_dispatch:
    inputs: {}
#  schedule:
#    - cron: '0 0 * * *' # Run the workflow every day at midnight UTC.

jobs:
  daily-cost-estimator:
    runs-on: [self-hosted, org, 8-cpu]
    steps:
      - uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev
          sudo apt-get install -y clang llvm-dev libclang-dev pkg-config

      - name: Run cost estimator
        run: |
          RUST_LOG=info cargo run --bin cost-estimator --release --features eigenda -- --batch-size 30 --default-range 1000
        env:
          L2_NODE_RPC: ${{ secrets.L2_NODE_RPC }}
          L1_RPC: ${{ secrets.L1_RPC }}
          L1_BEACON_RPC: ${{ secrets.L1_BEACON_RPC }}
          L2_RPC: ${{ secrets.L2_RPC }}
          EIGENDA_PROXY_ADDRESS: ${{ secrets.EIGENDA_PROXY_ADDRESS }}
          SP1_PROVER: mock
          OP_SUCCINCT_MOCK: true 

      - name: Upload execution reports
        uses: actions/upload-artifact@v4
        with:
          name: execution-reports
          path: execution-reports/ 