name: Docker Compose Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker-compose-test:
    name: Build the Docker Compose setup
    runs-on:
      - runs-on
      - cpu=16
      - ram=64
      - family=m7a+m7i-flex
      - image=ubuntu22-full-x64
      - run-id=${{ github.run_id }}    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.0
            network=host

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Compose setup
        run: |
          DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 \
          docker compose build \
            --build-arg BUILDKIT_INLINE_CACHE=1
