name: Docker Compose Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker-compose-test:
    name: Build the Docker Compose setup
    runs-on:
      - runs-on
      - cpu=16
      - ram=64
      - family=m7a+m7i-flex
      - image=ubuntu22-full-x64
      - run-id=${{ github.run_id }}    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Compose setup
        run: |
          docker compose build
