name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        working-directory: contracts/
        run: |
          forge --version

      - name: Run Forge fmt
        working-directory: contracts/
        run: |
          forge fmt --check src/ test/ script/
        id: fmt

      - name: Run Forge build
        working-directory: contracts/
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        working-directory: contracts/
        run: |
          forge test -vvv
        id: test
        env:
          L2_NODE_RPC: ${{ secrets.L2_NODE_RPC }}
          L1_RPC: ${{ secrets.L1_RPC }}
